### ISSUE TITLE
CRUD operations for budget and expenses

### ISSUE THREAD

**Issue by arifjehoh** [arifjehoh/expensify-rest#3]
The RESTful API should allow users to create, read, update, and delete budget and expenses. The API should provide endpoints for retrieving a list of all expenses, retrieving a single expense by ID, creating a new expense, updating an existing expense, and deleting an expense and vice versa for budget.

## Acceptance criteria:

- The API should provide endpoints for retrieving a list of all expenses, retrieving a single expense by ID, creating a new expense, updating an existing expense, and deleting an expense.
- The API should provide endpoints for retrieving a list of all budget, retrieving a single budget by ID, creating a new budget, updating an existing budget, and deleting an budget.
- The API endpoints should accept and return data in a standard format such as JSON.
- The API should handle errors gracefully and return appropriate error messages when necessary.
- The API should be thoroughly tested to ensure correct and consistent behavior.

## Tasks

- [ ] Read all budget
- [ ] Read one budget
- [ ] Create budget
- [ ] Update budget
- [ ] Delete budget
- [ ] Read all expense
- [ ] Read one expense
- [ ] Create expense
- [ ] Update expense
- [ ] Delete expense
- [ ] All data should return as JSON
- [ ] All data that comes in should be in JSON
- [ ] Error handling with a appropriate error message
- [ ] All endpoints should be tested.

**Comment by arifjehoh** [comment]
The expenses should have these field:
- id
- description
- date


Maybe I should also have created_at and updated_at fields?
I should maybe also have a budget id to be a reference to the budget.
